apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-resolver
  namespace: calico-networksets-controller
spec:
  selector:
    matchLabels:
      app: dns-resolver
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-resolver
    spec:
      containers:
      - name: dns-resolver
        image: ktrufanov/dns-resolver:0.0.1
        env:
        - name: SERVICE_PORT
          value: "8080"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dns-resolver
  namespace: calico-networksets-controller
  labels:
    app: dns-resolver
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: dns-resolver
